<?php

$cat_types=array("Computer Science and Engineering"=>"Computer Science and Engineering",
				"Accounting/Finance"=>"Accounting/Finance",
				"Bank/Non-Bank Fin. Institution"=>"Bank/Non-Bank Fin. Institution",
				"Commercial/Supply Chain"=>"Commercial/Supply Chain",
				"Customer Support/Call Centre"=>"Customer Support/Call Centre",
				"Data Entry/Operator/BPO"=>"Data Entry/Operator/BPO",
				"Design/Creative"=>"Design/Creative",
				"Electrician/ Construction/ Repair"=>"Electrician/ Construction/ Repair",
				"Education/Training"=>"Education/Training",
				"Engineer/Architect"=>"Engineer/Architect",
				"Garments/Textile"=>"Garments/Textile",
				"Hospitality/ Travel/ Tourism"=>"Hospitality/ Travel/ Tourism",
				"HR/Org. Development"=>"HR/Org. Development",
				"IT/Telecommunication"=>"IT/Telecommunication",
				"Law/Legal"=>"Law/Legal",
				"Marketing/Sales"=>"Marketing/Sales",
				"Media/Advertisement/Event Mgt."=>"Media/Advertisement/Event Mgt.",
				"Medical/Pharma"=>"Medical/Pharma",
				"Production/Operation"=>"Production/Operation",
				"Research/Consultancy"=>"Research/Consultancy",
				"Secretary/Receptionist"=>"Secretary/Receptionist",
				"Security/Support Service"=>"Security/Support Service",
				"Other"=>"Other"
				);
	$country_types=array("Bangladesh"=>"Bangladesh",
						  "India"=>"India",
						  "Pakistan"=>"Pakistan",
						   );	
	$business_types=array("Advertising Ageny",
							"Agro based firms",
							"Airline",
							"Architecture Firm",
							"Automobile",
							"Banks",
							"Bakery",
							"Bicycle",
							"Boutique/ Fashion",
							"BPO/ Data Entry Firm",
							"Buying House",
							"Call Center",
							"Chemical Industries",
							"Cinema Hall/Theater",
							"Coaching Center",
							"College",
							"Computer Hardware/Network Companies",
							" Consulting Firms",
							"Developer",
							"Development Agency",
							"E-commerce",
							"Engineering Firms",
							"Hospital",
							"Hotel",
							"Online Newspaper/ News Portal",
							"Restaurant",
							"Technical Infrastructure",
							"Telecommunication",
							"Textile"
							);					   
?>